name = "idea-to-market-saudi"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# Pages configuration
pages_build_output_dir = "dist"

# Environment variables
[vars]
ENVIRONMENT = "production"